language: node_js
node_js: '4'
sudo: false

install:
  - npm install
  - npm install -g bower

before_script:
  - bower install
  - gulp release

script:
  - "bash _build/deploy.sh"

branches:
  only:
    - master
    - staging

cache:
  apt: true
  directories:
    - node_modules

notifications:
  email: false
  slack: account:key
